class DiscordUserModel:
    def __init__(self, user_data):
        self.id = user_data.get("id", "")
        self.username = user_data.get("username", "")
        self.avatar = user_data.get("avatar", None)
        self.discriminator = user_data.get("discriminator", "")
        self.public_flags = user_data.get("public_flags", 0)
        self.premium_type = user_data.get("premium_type", 0)
        self.flags = user_data.get("flags", 0)
        self.bot = user_data.get("bot", False)
        self.banner = user_data.get("banner", None)
        self.accent_color = user_data.get("accent_color", None)
        self.global_name = user_data.get("global_name", None)
        self.avatar_decoration_data = user_data.get("avatar_decoration_data", None)
        self.banner_color = user_data.get("banner_color", None)
        self.mfa_enabled = user_data.get("mfa_enabled", False)
        self.locale = user_data.get("locale", "")
        self.email = user_data.get("email", None)
        self.verified = user_data.get("verified", False)
        self.bio = user_data.get("bio", "")
